---
version: 2.8.3
commit: 'chore(version): bump to v%.%.%'
files:
  README.md:
  - coveralls-gradle-plugin v%.%.%
  - id 'com.github.kt3k.coveralls' version '%.%.%'
  build.gradle:
  - version '%.%.%'
  gradle.properties:
  - VERSION_NAME=%.%.%
